# ===================================
#  Form Behavior Config
# ===================================

name: ompmega.blogauthors::lang.author.label
form: $/ompmega/blogauthors/models/author/fields.yaml
modelClass: Ompmega\BlogAuthors\Models\Author
defaultRedirect: ompmega/blogauthors/authors

create:
    title: ompmega.blogauthors::lang.author.create_author
    redirect: ompmega/blogauthors/authors/update/:id
    redirectClose: ompmega/blogauthors/authors

update:
    title: ompmega.blogauthors::lang.author.edit_author
    redirect: ompmega/blogauthors/authors
    redirectClose: ompmega/blogauthors/authors
